config/routes.rb
Rails
  .application
  .routes
  .draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    devise_for :users
    root 'home#landing'
  end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  ROLES = %i[user admin].freeze
  enum role: ROLES

  def admin?
    role.to_sym == :admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def authorize_admin
    redirect_to root_path, alert: "Permissions denied" unless
      current_user.admin?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:landing]

  def index
    render template: 'home/index'
  end

  def landing
    render template: 'home/landing'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(user_params)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    user_id = params[:id]
    @user = User.find(user_id)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(user_params)

    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(user_params)
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { head :ok }
    end
  end

  private

  def user_params
    params.permit(:name, :email, :password, :encrypted_password, :reset_password_token, :role, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/landing.html.erb
<h1>This is Modime</h1>
<p>Get Help Finishing Your Side Project</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Modime</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if notice %>
      <div><%= notice %></div>
    <% end %>
    <% if alert %>
      <div><%= alert %></div>
    <% end %>
    <% if user_signed_in? %>
      Logged in as a reg user: <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path  %>
    <% end %>
    <% if admin_signed_in? %>
    Logged in as an admin: <strong><%= current_admin.email %></strong> |
    <%= link_to 'Admin Portal', rails_admin_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p><%= f.label :name %><br />
    <%= f.text_field :name %></p>

  <p><%= f.label :email %><br />
    <%= f.email_field :email %></p>

  <% if action_name == "new" %>
    <p><%= f.label :password, "New password" %><br />
      <%= f.password_field :password %></p>

    <p><%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %></p>
  <% end %>

  <p>
    <%= f.label :role %><br />
    <%= f.collection_select :role, User::ROLES, :to_s, :to_s %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Edit user</h2>

<%= render 'form' %>
<%#= render 'passwords' %>

<%= link_to 'All users', users_path %>

app/views/users/index.html.erb
<h1>All Users</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Role</th>
    <th>Created At</th>
    <th>Updated At</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <th><%= user.name %></th>
      <th><%= user.email %></th>
      <th><%= user.role %></th>
      <th><%= user.created_at.to_s(:datetime).downcase %></th>
      <th><%= user.updated_at.to_s(:datetime).downcase %></th>
      <th><%= link_to "Edit", edit_user_path(user) %></th>
      <th><%= link_to "Delete", user, :method => :delete, :confirm => "Are you sure?" %></th>
    </tr>
  <% end %>
  </tbody>


</table>

<p><%= link_to "New User", new_user_path %></p>

app/views/users/new.html.erb
<h2>New User</h2>

<%= render 'form' %>

<%= link_to 'All users', users_path %>

app/views/users/show.html.erb
<p><%= @user.name %></p>
<p><%= @user.email %></p>
<p><%= @user.role %></p>